### ISSUE TITLE
Error when i use the react-filter-box

### ISSUE THREAD

**Issue by ravsom** [nhabuiduc/react-filter-box#6]
`error:  
peg$SyntaxError {message: "Expected "(" or category but end of input found.", expected: Array(2), found: null, location: Object, name: "SyntaxError"…}
expected
:
Array(2)
found
:
null
location
:
Object
message
:
"Expected "(" or category but end of input found."
name
:
"SyntaxError"
stack
:
"SyntaxError: Expected "(" or category but end of input found.↵    at peg$buildStructuredError (eval at compile (http://localhost:3000/assets/app.js:214235:18984), <anonymous>:328:14)↵    at Object.peg$parse [as parse] (eval at compile (http://localhost:3000/assets/app.js:214235:18984), <anonymous>:841:13)↵    at e.parseQuery (http://localhost:3000/assets/app.js:214235:121562)↵    at e.getSugessions (http://localhost:3000/assets/app.js:214235:121698)↵    at n.needAutoCompleteValues (http://localhost:3000/assets/app.js:214224:247342)↵    at e.needAutoCompletevalues (http://localhost:3000/assets/app.js:214235:119295)↵    at e.show (http://localhost:3000/assets/app.js:214235:117318)↵    at n.handlePressingAnyCharacter (http://localhost:3000/assets/app.js:214235:118848)↵    at http://localhost:3000/assets/app.js:214235:119713↵    at kt (http://localhost:3000/assets/app.js:214224:89070)"
__proto__
:
Error`

Do i need to set any other props to get this in order?

**Comment by ravsom** [comment]
I'm not sure what I did - but it sorted itself out. Sorry for the false alarm

**Comment by ravsom** [comment]
I still get this error - but doesn't seem to cause too much harm. What does it mean?
